server:
  port: 8000

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_ADDRESS}/demo?authSource=admin

  redis:
    host: ${REDIS_ADDRESS}
    port: 6379
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}
    timeout: 1000

cloud:
  env: ${CLOUD_ENV}

